### ISSUE TITLE
Only lint when phpmd.xml exists

### ISSUE THREAD

**Issue by mdeboer** [AtomLinter/linter-phpmd#102]
As I specify my PHPMD settings in a phpmd.xml ruleset file rather than globally in the plugin settings. It starts to complain every time I save when I work on a project that doesn't have a phpmd.xml file.

It would be wonderful to have an option to only lint when phpmd.xml exists **or** to check each file specified in the plugin settings for its existence. Now it just assumes it exists and shows a big error when it doesn't.

This would make linting with PHPMD much less obtrusive.

**Comment by Arcanemagus** [comment]
What exactly do you have in the settings for the Rulesets? It sounds like this is a much trickier issue than you are expecting as that setting must work for predefined rulesets within `phpmd` _and_ filenames of custom rulesets.

**Comment by mdeboer** [comment]
There's a couple of ways to fix this but I don't believe it will be that hard. The list of predefined rulesets is really small so you can exclude them. Also, I guess it's fair to say that custom rulesets usually reside in a ".xml" file.

Simply split by whitespace, check for any rules that end with ".xml" and if so, check if it exists. If it doesn't exist, either don't lint or exclude the file from the argument list when running PHPMD (I prefer the latter).

I'd be happy to give it a go 😄

**Comment by OriginalEXE** [comment]
Hi,

I think this is related so writing here and not opening a new issue. In this linter: https://github.com/AtomLinter/linter-phpcs there is an option to disable linting if the config file is not in the project. Can the same option be added to this linter?

Thanks for your hard work on this, love the packages!

**Comment by mdeboer** [comment]
@OriginalEXE I'm getting tired of the error message I'm getting in projects without phpmd.xml so I'm forking this and giving it the same options as linter-phpcs (which works fine).

I mean the mess detector does a good job at pissing me off sometimes but this is it, I've had it 😆

**Comment by mdeboer** [comment]
See #115
