### ISSUE TITLE
Project specific configuration

### ISSUE THREAD

**Issue by tillkruss** [AtomLinter/linter-phpmd#106]
I'm using the [Project Manager](https://atom.io/packages/project-manager) and on some project I have a custom `phpmd.xml` with PHPMD rules.

It would be nice to be either able to specify different PHPMD settings on a per project basis, or at least split up the "rulesets" input into two inputs. One for default rules and the other one for a `xml` file. If the file doesn't exists, then it falls back to the rules. See https://github.com/AtomLinter/linter-phpmd/issues/102

**Comment by Arcanemagus** [comment]
I'm a bit confused as to what you are asking here. It sounds like you are already using the only way I know of to implement project-specific settings (`project-manager`), so what configuration are you missing here?

Splitting the rulesets up as you suggest makes no sense because as far as PHPMD is concerned there is no difference.

**Comment by tillkruss** [comment]
Oh, is there a way to set specific `linter-phpmd` setting in the Project Manager? Right now the settings for PHPMD seem to be global

**Comment by Arcanemagus** [comment]
The settings are global, but the entire purpose of `project-manager` is to modify those global settings based on what project you have open 😛. In this case you would want to put a value for `linter-phpmd.rulesets` in the `settings` object for it.

**Comment by tillkruss** [comment]
This doesn't seem to work. Could you point me to the right syntax?

```cson
{
  title: "project title"
  group: "group name"
  paths: [
    "/path/to/project"
  ]
  settings:
    "linter-phpmd.rulesets": "phpmd.xml"
}
```

**Comment by Arcanemagus** [comment]
That looks like it should work to me from their example, maybe file an issue over there? I don't actually use the package myself.

**Comment by mdeboer** [comment]
See #115 to see if that fits your needs, it behaves the same like `linter-phpcs`. Project specific settings should be set in phpmd.xml.
