### ISSUE TITLE
Settings are not read correctly from `.atom/config.cson`

### ISSUE THREAD

**Issue by najela** [AtomLinter/linter-phpmd#12]
Here is a block  in my `.atom/config.cson` file

```
  "linter-phpmd":
    ShortVariable:
      minimum: 2
```

Here is a screenshot of the settings page 
<img width="994" alt="screen shot 2015-08-05 at 9 05 43 pm" src="https://cloud.githubusercontent.com/assets/4196457/9096563/c48f9322-3bb5-11e5-9cb4-b8a8e0963c4b.png">

Yet I still get an error saying that my minimum variable length is configured as 3 as seen below
<img width="1440" alt="screen shot 2015-08-05 at 9 07 00 pm" src="https://cloud.githubusercontent.com/assets/4196457/9096594/f0a8bad8-3bb5-11e5-9cc6-9bcafb057bee.png">

**Comment by Arcanemagus** [comment]
I'm not sure where that setting comes from as it isn't in the [current version](https://github.com/AtomLinter/linter-phpmd/blob/master/lib/main.coffee) of the linter...

Specifically the current version of the linter only supports (and utilizes) the Executable Path and the Rulesets.

**Comment by najela** [comment]
@Arcanemagus Isn't it possible for me to change the minimum length in phpmd?

**Comment by Arcanemagus** [comment]
Not from the [command line options](http://phpmd.org/documentation/index.html), which is all that the linter has access to. You would need to [create your own ruleset](http://phpmd.org/documentation/creating-a-ruleset.html) and specify the path to the XML file in your Rulesets list to do that.

**Comment by najela** [comment]
I created new rulewsets and they were applied correctly.
