### ISSUE TITLE
Closing files doesn't close the errors

### ISSUE THREAD

**Issue by Hansterdam** [AtomLinter/linter-phpmd#127]
When closing a file, the linter keeps displaying the errors for that file and in general it shows the errors of all open files. And since it doesn't even show for which files the errors are, there is no overview.

Is it possible to have it only show the errors of the file that is currently in focus? There doesn't seem to be a setting option for that either.

**Comment by Arcanemagus** [comment]
This is just a provider and has _nothing_ to do with the display of messages (or even running itself!). You'll need to file this on the UI package that you are using.

Thanks for taking the time to file an issue!

**Comment by Hansterdam** [comment]
Good to know. Thanks for letting me know!
