### ISSUE TITLE
"Mandatory arguments" error

### ISSUE THREAD

**Issue by rugk** [AtomLinter/linter-phpmd#38]
Juts after installing and editing a PHP file I get this error:

> Error: Mandatory arguments: 1) A php source code filename or directory. Can be a comma-separated string 2) A report format 3) A ruleset filename or a comma-separated string of rulesetfilenames

>Available formats: xml, text, html. Available rulesets: cleancode, codesize, controversial, design, naming, unusedcode.

>Optional arguments that may be put after the mandatory arguments: --minimumpriority: rule priority threshold; rules 

>```
Error: Mandatory arguments:
1) A php source code filename or directory. Can be a comma-separated string
2) A report format
3) A ruleset filename or a comma-separated string of rulesetfilenames

>Available formats: xml, text, html.
Available rulesets: cleancode, codesize, controversial, design, naming, unusedcode.

>Optional arguments that may be put after the mandatory arguments:
--minimumpriority: rule priority threshold; rules with lower priority than this will not be used
--reportfile: send report output to a file; default to STDOUT
--suffixes: comma-separated string of valid source code filename extensions
--exclude: comma-separated string of patterns that are used to ignore directories
--strict: also report those nodes with a @SuppressWarnings annotation

>    at parameters.exit (D:\Users\%username%\.atom\packages\linter-phpmd\node_modules\atom-linter\lib\helpers.js:58:20)
    at triggerExitCallback (C:\Users\%username%\AppData\Local\atom\app-1.3.2\resources\app.asar\src\buffered-process.js:213:47)
    at ChildProcess.<anonymous> (C:\Users\%username%\AppData\Local\atom\app-1.3.2\resources\app.asar\src\buffered-process.js:235:18)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
```

**Comment by Arcanemagus** [comment]
What does your configuration look like?

**Comment by rugk** [comment]
I've just set up the path to the phpmd.phar. The rulesets are the default ones.

![configphpmd](https://cloud.githubusercontent.com/assets/11966684/12033934/f32ec946-ae29-11e5-8c12-bf6910391962.PNG)

When this package activated I get this error every time I save a PHP file.

**Comment by Arcanemagus** [comment]
Hmmm, so the way this project is tested is to run the `phpmd` executable, whatever that may be on the system. Since I installed through Composer it is a batch script consisting of the following:

```batch
@ECHO OFF
SET BIN_TARGET=%~dp0/../phpmd/phpmd/src/bin/phpmd
php "%BIN_TARGET%" %*
```

Which should be largely the same if you have set up the extension executable for `.phar` files on your system.

Can you open Atom's developer tools and put a breakpoint on [this line](https://github.com/AtomLinter/linter-phpmd/blob/v1.3.2/lib/main.coffee#L59) and see what the contents of command and parameters are?

**Comment by rugk** [comment]
Based on the Batch script you gave me I think I know what the issue is. This file is obviously not opened with PHP.

So I've just changed my config and added `php ` before the path to the .phar.

Now I get another error, which is basically a syntax error as Windows complains about the path syntax:
```
Error: Die Syntax f�r den Dateinamen, Verzeichnisnamen oder die Datentr�gerbezeichnung ist falsch.
    at parameters.exit (D:\Users\%username%\.atom\packages\linter-phpmd\node_modules\atom-linter\lib\helpers.js:58:20)
    at triggerExitCallback (C:\Users\%username%\AppData\Local\atom\app-1.3.2\resources\app.asar\src\buffered-process.js:213:47)
    at C:\Users\%username%\AppData\Local\atom\app-1.3.2\resources\app.asar\src\buffered-process.js:227:18
    at Socket.<anonymous> (C:\Users\%username%\AppData\Local\atom\app-1.3.2\resources\app.asar\src\buffered-process.js:98:18)
    at emitOne (events.js:82:20)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
```

**Comment by Arcanemagus** [comment]
No, the error you posted at the beginning was what `phpmd` prints when you don't give it parameters it understands, so it seemed to be running `phpmd` properly, just not sending it the right parameters.

**Comment by Arcanemagus** [comment]
Also what do you get from running `phpmd --version`?

**Comment by rugk** [comment]
Hmm... okay, so one step back.

```ShellSession
D:\XAMPP\phplib>php phpmd.phar --version
PHPMD 2.3.2
```

**Comment by Arcanemagus** [comment]
Well, it's not an issue with an out of date version of `phpmd` at least. Have you been able to set the breakpoint yet and see what parameters it is trying to pass in?

**Comment by rugk** [comment]
I'll try. Just discovered a new issue with this breakpoint: https://github.com/AtomLinter/linter-phpmd/issues/39

**Comment by rugk** [comment]
Here is what Atom shows me:
![argumentserror](https://cloud.githubusercontent.com/assets/11966684/12042500/0a6dde92-ae7c-11e5-8c59-c3226fa2685b.PNG)

**Comment by Arcanemagus** [comment]
Can you try creating a wrapper batch script (like the one posted earlier) that launches the phar for you? Everything looks correct, with the only difference being you are directly launching the .phar. I'm wondering if something about the environment it is launched in doesn't handle that. I know that node used to have issues with `.bat` files, I'm wondering if when fixing that they _only_ fixed it for `.bat` instead of generic executable extension support.

**Comment by rugk** [comment]
Okay.

So with a batch file I could find out that it is called like this:
``` 
C:\Windows\system32\cmd.exe /s /c "D:\XAMPP\phplib\phpmdwrapper.bat "D:\XAMPP\phplib\test.php" "text" "cleancode,codesize,controversial,design,naming,unusedcode""
```

So if you take the batch part away here you get the parameters passed to phpmd:
```
"D:\XAMPP\phplib\test.php" "text" "cleancode,codesize,controversial,design,naming,unusedcode"
```

In a more abstract way:
```
<file> "text" <rulesets>
```

And by passing them to phpmd.phar manually I also get these errors:
```
D:\XAMPP\phplib>phpmd.phar "D:\XAMPP\phplib\test.php" "text" "cleancode,codesize
,controversial,design,naming,unusedcode"
Mandatory arguments:
1) A php source code filename or directory. Can be a comma-separated string
2) A report format
3) A ruleset filename or a comma-separated string of rulesetfilenames

Available formats: xml, text, html.
Available rulesets: cleancode, codesize, controversial, design, naming, unusedco
de.

Optional arguments that may be put after the mandatory arguments:
--minimumpriority: rule priority threshold; rules with lower priority than this
will not be used
--reportfile: send report output to a file; default to STDOUT
--suffixes: comma-separated string of valid source code filename extensions
--exclude: comma-separated string of patterns that are used to ignore directorie
s
--strict: also report those nodes with a @SuppressWarnings annotation
```

**Comment by Arcanemagus** [comment]
Sounds like something is wrong with your `phpmd` installation, running from the command line should work fine...

![image](https://cloud.githubusercontent.com/assets/427137/12043526/a7176fde-ae3a-11e5-83ab-e83757144d8e.png)

**Comment by rugk** [comment]
Note that I have some strange open-with "bindings" for `.phar` files in my registry (added manually) and these may cause the error.

See this example:
```
> php phpmd.phar --version
PHPMD 2.3.2

> phpmd.phar --version

>
```

Actually this is a faked command result, but this is how it looked before a minute. Currently also passing it to `php` directly does not work and this is very strange, but I'll look into this.

But generally my adaptions of `.phar` "open with" entries are only manually and if you install phpmd in the way I did on Windows, you generally cannot execute `.phar` files out-of-the-box and you always have to call them with php (`php file.phar`) to work.
So maybe this should be done in this package too as it can lead to more errors if you just try to open a `.phar` file like it is.
AFAIK this is how [php-cs-fixer](https://github.com/pfefferle/atom-php-cs-fixer) does it and it makes this much failsafer.

**Comment by Arcanemagus** [comment]
`php-cs-fixer` would be completely broken if you followed their instructions on a Windows machine.

![image](https://cloud.githubusercontent.com/assets/427137/12044150/af1dc816-ae41-11e5-9935-6dbc225f046f.png)

Running things like they do is only correct for running the phar directly, which is only useful if you don't have the program installed properly in the first place. I would highly recommend you use Composer (Or PEAR, but it's often rather outdated) to install `phpmd` on your system.

**Comment by rugk** [comment]
> You haven't _installed_ `phpmd` yet, you have only downloaded the .phar file. Granted you can _run_ this, but it isn't _installed_ on your computer in any meaningful sense.

But this is the way they describe it on their website - so even if installing via Composer or something like this would be better, I think only a few people will do this when they read the documentation there.

**Comment by Arcanemagus** [comment]
@rugk It looks like this discussion kinda... trailed off. Do you understand what I mean when I'm saying it isn't installed and this issue can be closed, or did you have more to bring up?
