### ISSUE TITLE
Custom ruleset

### ISSUE THREAD

**Issue by Trudko** [AtomLinter/linter-phpmd#4]
Hi, first of all thank you for plugin! :)

I would like to ask you if you are planning to provide way how to set custom ruleset(by providing path to XML for example).?

**Comment by binarious** [comment]
+1 for this feature

**Comment by Arcanemagus** [comment]
With the way PHPMD handles rulesets, you should be able to just add the path to it's XML file into the list of rulesets in the settings. PHPMD essentially handles _all_ rulesets as custom, it just has predefined constants for some :wink:.

Is that not working for you?

**Comment by binarious** [comment]
It is working for me, thank you!

**Comment by steelbrain** [comment]
Closing as it's working already
