### ISSUE TITLE
Miss being able to specify filename for automatic ruleset

### ISSUE THREAD

**Issue by torkiljohnsen** [AtomLinter/linter-phpmd#58]
I have multiple XML files for rulesets, like phpunit.xml, phpmd.xml, phpcs.xml.

It would be nice to be able to specify a filename different from the very general "ruleset.xml".

**Comment by torkiljohnsen** [comment]
And, when I try to specify phpmd.xml in the PHPMD rulesets setting field, I get the error "cannot find specified rule-set phpmd.xml". Looks like it's somehow not searching among the project files…? If I run phpmd on the commandline, from my project root folder where the phpmd.xml file is located, and specify phpmd.xml as my ruleset, it works fine.

**Comment by stipsan** [comment]
I'll work on a PR for this.
