### ISSUE TITLE
Error: Property "ignorepattern" does not exist.

### ISSUE THREAD

**Issue by binarious** [AtomLinter/linter-phpmd#66]
On linting:
```
Error: Property "ignorepattern" does not exist.
    at ChildProcess.<anonymous> (/Users/myuser/.atom/packages/linter-phpmd/node_modules/atom-linter/node_modules/sb-exec/lib/index.js:36:20)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:818:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
```

The console is not showing anything.

Package | Version
------------ | -------------
linter | 1.11.14
linter-phpmd | 1.5.0
phpmd | 2.4.3
OS X | 10.11.5
Atom | 1.8.0

Any ideas how to fix this?

**Comment by Arcanemagus** [comment]
Hmmmm, does `phpmd` work if you run it from the CLI?

**Comment by binarious** [comment]
Yes it does.

Landon Abney <notifications@github.com> schrieb am Do., 23. Juni 2016,
18:58:

**Comment by Arcanemagus** [comment]
From the stack trace as far as I can tell that error is coming from `phpmd`, so I'm not really sure where it could be coming from if `phpmd` works on the CLI.

If you close _all_ instances of Atom, and then launch it from the same directory you tried `phpmd` in with `atom .`, does it work then?

**Comment by binarious** [comment]
It was a problem with a ruleset definition which was too old.
