### ISSUE TITLE
Error: spawn phpmd ENOENT

### ISSUE THREAD

**Issue by rshmiraf** [AtomLinter/linter-phpmd#80]
Hi,
Im beginner in composer. Could you resolve this? Thanks!

![zrzut ekranu 2016-07-30 o 16 42 56](https://cloud.githubusercontent.com/assets/14861637/17271148/e915702e-5674-11e6-9958-f713cb0b2f70.png)
![zrzut ekranu 2016-07-30 o 16 47 42](https://cloud.githubusercontent.com/assets/14861637/17271176/5d28a13e-5675-11e6-9bdc-a264133aae9f.png)

**Comment by rafa-acioly** [comment]
same problema here.

**Comment by Arcanemagus** [comment]
Have you added your vendor bin-dir to your `$PATH`? It's likely you need to add `/Users/schmidt/.composer/vendor/bin` to your path.

You should be able to run `which phpmd` and get a result back.

**Comment by Arcanemagus** [comment]
Marking as closed due to a lack of response.
