### ISSUE TITLE
Scan multiple project folders

### ISSUE THREAD

**Issue by hultberg** [AtomLinter/linter-phpmd#85]
Hello!
In atom I have two project folders, one for the project and one for the library it requires. I observe that linter-phpmd warns about undefined global constants that are defined the second project folder. There should be support for this? Compare it to the "Include folders" in phpstorm

**Comment by Arcanemagus** [comment]
Does `phpmd` itself handle that? This project merely forwards on the messages it produces.

**Comment by hultberg** [comment]
@Arcanemagus No, I don't belive this is a feature in phpmd. Surfed trough some issues and found that they are not planning to add support for it in the near future.

**Comment by Arcanemagus** [comment]
Marking this as closed for now then, since this is merely a "translator" between `phpmd` and the `linter` Atom package.

If `phpmd` ever adds support for something like this feel free to reopen this or file a new issue 😉.
